// app/layout.tsx

import type { Metadata } from "next";
import { ReactNode } from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSessionProvider from './ClientSessionProvider';

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
    children: ReactNode;
    session?: any; // Adjust this type as needed for your session data
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, session }: LayoutProps) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ClientSessionProvider session={session}>
                    {children}
                </ClientSessionProvider>
            </body>
        </html>
    );
}
