export default function HomePage() {
    return (
        <div className="border-red-900 border-2 grow flex-1 flex flex-col h-full">
            <h1 className="bg-red-200">Welcome to Create Next App!</h1>
            <p>Generated by create next app </p>
        </div>
    );
}
